---
- name: Install Web Server
  hosts: linux
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name: "{{ item }}"
      with_items:
        - nginx
        - curl
      when: ansible_os_family == "Debian"
    - name: Install required packages
      ansible.builtin.package:
        name: "{{ item }}"
      with_items:
        - httpd
        - curl
      when: ansible_os_family == "RedHat"

    - name: Start Apache service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      when: ansible_os_family == "RedHat"

    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      when: ansible_os_family == "Debian"
